# example config: suited for working in gradient notebooks

train-dirs:
  - /datasets/xview2/train
  #- /datasets/xview2-mini/tier3

test-dirs:
  - /datasets/xview2/test/

dir-names:
  images: images
  labels: labels
  masks: targets
  localization: pred_loc_val

predictions-dir: /root/pred/
submissions-dir: /root/submissions/
model-weights-dir: /root/weights/
