# example config: suited for working in gradient notebooks

train-dirs:
  - /datasets/xview2-mini/train
  #- /datasets/xview2-mini/tier3

test-dirs:
  - /datasets/xview2-mini/test/

dir-names:
  images: images
  labels: labels
  masks: targets
  localization: pred_loc_val

predictions-dir: ./data/pred/
submissions-dir: ./data/submissions/
model-weights-dir: ./data/weights/
